### ISSUE TITLE
Issue when trying to write to a file

### ISSUE THREAD

**Issue by muralirvce** [colinmarc/hdfs#103]
Hi, I have around 60 files open and am writing in parallel to them but am running into following issue:
bytes.(*Buffer).grow(0xc43ece5a58, 0x2a9, 0xc4466c1510)
	/home/murali/workspace_bigdata/toolchain-builds/a96902dd2a80fc9a82499929dea71a5742a0e607.x86_64/go/src/bytes/buffer.go:130 +0x274
bytes.(*Buffer).Write(0xc43ece5a58, 0xc43728f900, 0x2a9, 0x4cd, 0x51a52f, 0xc42d34b160, 0x0)
	/home/murali/workspace_bigdata/toolchain-builds/a96902dd2a80fc9a82499929dea71a5742a0e607.x86_64/go/src/bytes/buffer.go:163 +0xdd
github.com/colinmarc/hdfs/rpc.(*blockWriteStream).Write(0xc43ece5a40, 0xc43728f900, 0x2a9, 0x4cd, 0xc42d34b160, 0xc42d34b188, 0x50df17)
	/home/murali/go/src/github.com/colinmarc/hdfs/rpc/block_write_stream.go:101 +0x93
github.com/colinmarc/hdfs/rpc.(*BlockWriter).Write(0xc422244140, 0xc43728f900, 0x2a9, 0x4cd, 0xb, 0xad6e01, 0xd20000c4304d3530)
	/home/murali/go/src/github.com/colinmarc/hdfs/rpc/block_writer.go:76 +0x8d
github.com/colinmarc/hdfs.(*FileWriter).Write(0xc4368c7880, 0xc43728f900, 0x2a9, 0x4cd, 0xc425fdc158, 0x1, 0x0)
	/home/murali/go/src/github.com/colinmarc/hdfs/file_writer.go:163 +0xa3

**Comment by colinmarc** [comment]
Hi @muralirvce, 

Are you sure that's the whole traceback? Looks like it's missing the panic message.

**Comment by muralirvce** [comment]
It is not the full back trace here it is...

goroutine 636 [running]:
bytes.(*Buffer).grow(0xc4231a12d8, 0x11b, 0xc439b08fd0)
	/home/murali/workspace_bigdata/toolchain-builds/a96902dd2a80fc9a82499929dea71a5742a0e607.x86_64/go/src/bytes/buffer.go:130 +0x274
bytes.(*Buffer).Write(0xc4231a12d8, 0xc439b14c00, 0x11b, 0x161, 0x51a52f, 0xc42d48f160, 0x0)
	/home/murali/workspace_bigdata/toolchain-builds/a96902dd2a80fc9a82499929dea71a5742a0e607.x86_64/go/src/bytes/buffer.go:163 +0xdd
github.com/colinmarc/hdfs/rpc.(*blockWriteStream).Write(0xc4231a12c0, 0xc439b14c00, 0x11b, 0x161, 0xc42d48f160, 0xc42d48f188, 0x50df17)
	/home/murali/go/src/github.com/colinmarc/hdfs/rpc/block_write_stream.go:101 +0x93
github.com/colinmarc/hdfs/rpc.(*BlockWriter).Write(0xc422be2550, 0xc439b14c00, 0x11b, 0x161, 0x4, 0xad6e01, 0xde0000c42c24a6f0)
	/home/murali/go/src/github.com/colinmarc/hdfs/rpc/block_writer.go:76 +0x8d
github.com/colinmarc/hdfs.(*FileWriter).Write(0xc420fb94c0, 0xc439b14c00, 0x11b, 0x161, 0xc424f18168, 0x1, 0x0)
	/home/murali/go/src/github.com/colinmarc/hdfs/file_writer.go:163 +0xa3
Last_Func1(0xc420266140, 0xc426ddca00, 0x32, 0x40, 0xc421f61400, 0xc42d48f458, 0x52f807)
	/home/murali/workspace_bigdata/main/.go/src/nusights/server/db/interface/hdfs/hdfs_client.go:136 +0x30f
Last_Func2(0xc420266140, 0xc4200952c0, 0xc421f61400, 0x1, 0x1)
	hdfs_client.go:83 +0x7a
LastFunc3(0xc42000e388, 0xc4200952c0, 0xc421f61400, 0x1, 0x1)
	hdfs_handlers.go:66 +0x42
LastFunc4(0xc420107920, 0xc4200952c0, 0xc421f61400, 0xc4223a2710, 0xc422b75168)
	if.go:131 +0x61
LastFunc5(0xc4201078a0, 0xc422ada000, 0x32, 0x32, 0x3)
	consumer.go:218 +0x21d3
LastFunc6(0xc4213c2120, 0xc420172820, 0x32, 0x32)
	parallel.go:113 +0x3da
LastFunc7(0xc4213c2120, 0x1, 0xc420597080, 0xc420617da0, 0xc420252360)
	parallercaller.go:195 +0x4ef
LastFunc8
	consumer.go:307 +0x1f1

**Comment by muralirvce** [comment]
I have identified the problem. This is not a issue. I was using the client parallely across two consumers. I am sorry for the trouble.
