### ISSUE TITLE
CopyToLocal get error,  getFileInfo call failed with ERROR_APPLICATION (org.apache.hadoop.fs.InvalidPathException)

### ISSUE THREAD

**Issue by SummerBuger** [colinmarc/hdfs#105]
#### Version Info:
| PROJECT | CONSTRAINT | VERSION | REVISION | LATEST | PKGS USED |
| --------- | -------------- | ---------- | ---------- | ------- | ------------ |
| github.com/colinmarc/hdfs  | ^1.1.0 | v1.1.0 | 69e5098 | v1.1.0 | 4  |

#### Go Version
go version go1.9.2 darwin/amd64

#### Code
```go
package main

import (
	"log"

	"github.com/colinmarc/hdfs"
)

func main() {
	//e92h13512.em21
	client, err := hdfs.New("namenode:8020")
	if err != nil {
		log.Fatalf("Connect to hdfs server get error: %v\n", err)
	}
	err = client.CopyToLocal("hdfsFilePath",
		"localFilePath")
	if err != nil {
		log.Fatalf("Copy hdfs file to local get error: %v\n", err)
	}
	err = client.Close()
	if err != nil {
		log.Fatalf("Close the hdfs client get error: %v\n", err)
	}
	log.Printf("Close the hdfs client\n")
}
```

#### Error Info
```
2018/03/** **:**:** Copy hdfs file to local get error: open chaochun.chen/brand/forecast/traffic/cpm/cpm_base_predict_20180313.txt: getFileInfo call failed with ERROR_APPLICATION (org.apache.hadoop.fs.InvalidPathException)
```

**Comment by SummerBuger** [comment]
@colinmarc  Can you help me ?

**Comment by colinmarc** [comment]
Hi @SummerBuger,

ErrorApplication indicates that the error is coming from HDFS, not the library. In this case, it looks like you're missing the ’/’ at the beginning of the path.

**Comment by SummerBuger** [comment]
I'm not missing the ’/’ at the beginning of the path.
In other words, I have no permission  to create a subfoler of '/'.
And I can use hadoop command to copy the hdfs file to local.
```
hadoop fs -get chaochun.chen/brand/forecast/traffic/cpm/cpm_base_predict_20180313.txt
```

**Comment by colinmarc** [comment]
Ah - sorry for the confusion. `hadoop fs` is translating the path to be inside your "home directory", in that case. The library doesn't do that. HDFS has a poorly defined idea of a "home directory", and the command line client (but not the library) respects that convention just for compatibility:

```
func userDir() string {
	currentUser, err := hdfs.Username()
	if err != nil || currentUser == "" {
		return "/"
	}

	return path.Join("/user", currentUser)
}
```

If you're using the library, you should use absolute paths. In this case that would be `/user/<username>/chaochun.chen/brand/forecast/...`.
