### ISSUE TITLE
how this client handles HDFS HA?

### ISSUE THREAD

**Issue by twang333** [colinmarc/hdfs#106]
when only one namenode is used, I encounter following problem: 
no available namenodes: getFileInfo call failed with ERROR_APPLICATION (org.apache.hadoop.ipc.StandbyException).

Then, multiple namenodes are used. But, this problem still exists.  Any tips? 
BTW, HDFS Java client don't have this problem. Thanks

**Comment by colinmarc** [comment]
@twang333 are you definitely passing all the namenodes in when connecting? That's pretty strange.

**Comment by colinmarc** [comment]
Going to close this for lack of information. Please feel empowered to reopen!
