### ISSUE TITLE
HDFS data below 64KB not flushed to HDFS

### ISSUE THREAD

**Issue by muralirvce** [colinmarc/hdfs#107]
Hi,
    I see that data is sent in 64KB packets to the hdfs datanode in rpc requests. But if there is not data pending say 63KB then if it takes more than a minute for the data to arrive the rpc connection will be closed and the data will not be written. Would it be good to add a flush routine on the writer to help in such scenarios?

Thanks,
Murali

**Comment by colinmarc** [comment]
Hi @muralirvce,

Are you making sure to call `Close`? The documentation calls this out:

> Because of the way that HDFS writes are buffered and acknowledged asynchronously, it is very important that Close is called after all data has been written.

Or do you mean when keeping a file open for more than an hour?

**Comment by muralirvce** [comment]
I call close, but before that the timeout has expired. I write data every 30 seconds once like 5KB, we do not have 64KB to flush. Hence we will not send the data out until we get 64KB. By the time we close the connection could have timedout. IMO we can add a flush routing to the FileWriter class. I have done some changes, can submit the patch if needed.

**Comment by colinmarc** [comment]
There might be a keepalive we can send, rather than flushing. I'd have to research.

**Comment by muralirvce** [comment]
Keepalive sounds good. IMO Adding a flush also might not be a bad idea, incase if the data has to be visible. Only part is the block length will not be updated but the data is present. Block reporting will happen when we close. Please let me know your take on it. It is like any other file system writer.

**Comment by colinmarc** [comment]
I exposed `FileWriter.Flush` and added some tests around it.
