### ISSUE TITLE
Is there any configure function to add  dfs.client.use.datanode.hostname ?

### ISSUE THREAD

**Issue by tyhtao1990** [colinmarc/hdfs#118]
my hdfs datanode must connect with a hostname , I find source code read datanode by IP default and can't change to read by hostname so I changed the function getDatanodeAddress() to get the datanode address from hostname.
Is there any better way to fix this problem?

**Comment by colinmarc** [comment]
Hi @tyhtao1990,

Not currently, but it would be pretty straightforward to do as an option in `ClientOptions` (and also parse out of the conf).
