### ISSUE TITLE
How do I determine if a file exists or not, is there a supported method to use?

### ISSUE THREAD

**Issue by xxh2000** [colinmarc/hdfs#119]

**Comment by colinmarc** [comment]
Hi @xxh2000,

You can use [`Stat`](https://godoc.org/github.com/colinmarc/hdfs#Client.Stat). The method works just like [`os.Stat`](https://golang.org/pkg/os/#File.Stat).

Hope that helps!

**Comment by xxh2000** [comment]
ok, thanks!
