### ISSUE TITLE
wsarecv: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by xxh2000** [colinmarc/hdfs#121]
When I connect hdfs, after writing data to the file over time, an exception occurs. The error message is established connection was aborted by the software in your host machine. What is the reason for this? How to solve it?

**Comment by colinmarc** [comment]
Hi @xxh2000, sorry for the super late response! I'm not really sure what that might be. Do you mind submitting a test case?

**Comment by colinmarc** [comment]
Going to close this, but feel free to reopen if you have more information.
