### ISSUE TITLE
Is support Hadoop -text cmd?

### ISSUE THREAD

**Issue by hxfxjun** [colinmarc/hdfs#122]
$ hadoop fs -help text
-text [-ignoreCrc] <src> ...:	Takes a source file and outputs the file in text format.
		The allowed formats are zip and TextRecordInputStream and Avro.

I want read gzip file on hdfs, usually use hadoop fs -text cmd in java.

**Comment by colinmarc** [comment]
Hi @hxfxjun, sorry for the late reply. Is what you want achieved by `hdfs cat ... | gzip`?

**Comment by colinmarc** [comment]
This seems equivalent:

```
$ echo "foo" | gzip | hdfs put - /user/colinmarc/foo.txt.gz
$ hadoop fs -text /user/colinmarc/foo.txt.gz
foo
$ ./hdfs cat /user/colinmarc/foo.txt.gz | gunzip -c
foo
```

Also, in case it's relevant, I wrote a sequencefile implementation with decompression support a while ago. It's available here: https://github.com/colinmarc/sequencefile

So I'm going to close this, but feel free to reopen if I got something wrong!
