### ISSUE TITLE
Enable the ability of Blockwriter to recover from write failure

### ISSUE THREAD

**Issue by wangdfgithub** [colinmarc/hdfs#124]
Now, blockwriter are not able to recover from write failure, it introduces several problems: eg, when try to flush/write, an data-node is lost, then this action will fail, it's painful for customer. are there anyone else encounter the similar issue?

**Comment by colinmarc** [comment]
Hi @wangdfgithub, 

There's already an issue and some context for this here: #86 

As such, I'm going to close this.
