### ISSUE TITLE
hdfs client fails with "netpoll failed" on RHEL5

### ISSUE THREAD

**Issue by dwierenga** [colinmarc/hdfs#126]
I have an old RHEL5 machine that I was trying to use the command line client on.  I ran `hdfs ls /` and it fails with:
>runtime: epollwait on fd 4 failed with 38
> fatal error: runtime: netpoll failed

Using  with the same `HADOOP_NAMENODE` value on RHEL6, I get the expected output.

**Comment by colinmarc** [comment]
Hi @dwierenga, sorry for the super late response. Are you using the compiled release or compiling by yourself? This sounds like a RHEL5 issue to me.

**Comment by dwierenga** [comment]
I was using the compiled release.

**Comment by colinmarc** [comment]
@dwierenga can you try setting up go and running `go get -u github.com/colinmarc/hdfs/cmd/hdfs` and tell me if it exhibits the same problem? That'll indicate whether it's a build issue or a general issue.

**Comment by colinmarc** [comment]
Going to close this, since I haven't heard anything and I don't have a RHEL5 machine handy to test. Please let me know if you have any new information.

**Comment by xzy256** [comment]
I have RHEL5 and RHEL6 machines. Tested hdfs on RHEL5 and RHEL6.  Go version 1.9.  
RHEL5 kernel is low, lacking `epoll_pwait ` system call.  so you get `Errno value 38(ENOSYS).`
RHEL6 can run correctly.

**Comment by colinmarc** [comment]
Yeah, the releases probably just don't support RHEL5. You should be able to build from source, though.
