### ISSUE TITLE
Parsing namenode addresses from conf includes logical names

### ISSUE THREAD

**Issue by systm32** [colinmarc/hdfs#127]
As if namenode address is not provided, the client picks it up from the conf files (core-site.xml, hdfs-site.xml). In my case what was happening is in core-site.xml we have defined fs.defaultFS property value as "mycluster" which is a logical name. The resolve connection method in namenode.go is throwing error "no name nodeaddress: address mycluster: missing port in address" after the failover. Not sure if this is a known issue?

**Comment by colinmarc** [comment]
Hi @systm32, this does sound like a bug. Can you share your core-site.xml with me? You can send it to colinmarc@gmail.com if you prefer, or just put it in a gist with things anonymized.
