### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by systm32** [colinmarc/hdfs#128]
I was testing failover of a node(say 1) in a three node cluster(say 1, 2, 3) and if the hdfs connection is established to namenode 1 by some application running on the node 2. After the failover completes and node comes back, the application running on node 2 tries to perform some operation on hdfs it does able resolve the connection made to node 1 (before failover) but ReadResponse method in Execute is returning "connection reset by peer" and this error is returned to the application.

Shouldn't the hdfs-client retry on receiving this exception as it is doing for standby exception to handle the failover?

**Comment by colinmarc** [comment]
Hi @systm32! This is a good point, but it's been brought up before in #65, so I'm going to close this as a duplicate.
