### ISSUE TITLE
dep error: code.google.com/p/goprotobuf/proto

### ISSUE THREAD

**Issue by fengjingchao** [colinmarc/hdfs#13]
Hi @colinmarc 

It looks like the google code path is moved completely to https://github.com/golang/protobuf
```
package github.com/colinmarc/hdfs
	imports code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path
```
Would you mind to change the import path? Thanks!

**Comment by colinmarc** [comment]
Fixed! Sorry about the delay.
