### ISSUE TITLE
Hdfs lease issue?

### ISSUE THREAD

**Issue by xxh2000** [colinmarc/hdfs#134]
Hdfs has a lease rule. If the file operation time exceeds the lease time (usually 1h), is there a way to provide renewal? In the Java program, there is a background thread in the DFSClient that has been checking the lease and renewing it when it expires. Does the library also have this method of operation?

**Comment by colinmarc** [comment]
I believe this is a duplicate of #60 - please feel free to reopen if I have that wrong!
