### ISSUE TITLE
failed go get -u github.com/colinmarc/hdfs due to v2?

### ISSUE THREAD

**Issue by chrislusf** [colinmarc/hdfs#142]
chris:hdfs chris$ go get -u github.com/colinmarc/hdfs
package github.com/colinmarc/hdfs/v2/hadoopconf: cannot find package "github.com/colinmarc/hdfs/v2/hadoopconf" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOROOT)
	/Users/chris/dev/gopath/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOPATH)
package github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs: cannot find package "github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOROOT)
	/Users/chris/dev/gopath/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOPATH)
package github.com/colinmarc/hdfs/v2/internal/rpc: cannot find package "github.com/colinmarc/hdfs/v2/internal/rpc" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOROOT)
	/Users/chris/dev/gopath/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOPATH)

**Comment by colinmarc** [comment]
What's your go version?

**Comment by chrislusf** [comment]
chris:hdfs chris$ go version
go version go1.10 darwin/amd64

**Comment by chrislusf** [comment]
Consider to avoid the versioning "v2" later? Hard to understand how the versioning works and how to fix it.

**Comment by chrislusf** [comment]
btw: this used to work fine.

**Comment by colinmarc** [comment]
Yup - I'm really sorry for the confusion. Can you check whether you have this patch? https://github.com/golang/go/issues/25139

Should be in 1.10.3.

**Comment by chrislusf** [comment]
upgrading to 1.10.3 works! Thanks!

This is used in a open-sourced library. "go get" is easy to pick up.

**Comment by fanfansong** [comment]
But if you move code into vendor directory， it happend again.

**Comment by sinylei** [comment]
Still not working.

go get github.com/colinmarc/hdfs
Desktop/gowork/src/github.com/colinmarc/hdfs/client.go:14:2: use of internal package github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs not allowed
Desktop/gowork/src/github.com/colinmarc/hdfs/client.go:15:2: use of internal package github.com/colinmarc/hdfs/v2/internal/rpc not allowed

$ go version
go version go1.11.2 darwin/amd64

**Comment by pmalekn** [comment]
It also doesn't work on `go1.10.7 darwin/amd64` with `glide`

```
[INFO]  Found Gomfile in /Users/USER/.glide/cache/src/https-github.com-grafov-m3u8
[INFO]  --> Parsing Gomfile metadata...
[INFO]  --> Fetching updates for github.com/opentracing/opentracing-go
[INFO]  --> Fetching updates for google.golang.org/grpc
[INFO]  --> Fetching updates for go.opencensus.io
[ERROR] Error scanning github.com/colinmarc/hdfs/v2/hadoopconf: cannot find package "." in:
        /Users/USER/.glide/cache/src/https-github.com-colinmarc-hdfs/v2/hadoopconf
[ERROR] Error scanning github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs: cannot find package "." in:
        /Users/USER/.glide/cache/src/https-github.com-colinmarc-hdfs/v2/internal/protocol/hadoop_hdfs
[ERROR] Error scanning github.com/colinmarc/hdfs/v2/internal/rpc: cannot find package "." in:
        /Users/USER/.glide/cache/src/https-github.com-colinmarc-hdfs/v2/internal/rpc
```

which is a pain because it's a transitive dependency and I have my hands tied. Any ideas on how to approach this?

**Comment by pseudocodes** [comment]
would you please just rename the ‘internal’ package ?
