### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by tenghuan** [colinmarc/hdfs#143]
hello, I run the command "go get github.com/colinmarc/hdfs" on centos
but meet the error as below:
-----------------------------------------------------------------------------------
package github.com/colinmarc/hdfs/v2/hadoopconf: cannot find package "github.com/colinmarc/hdfs/v2/hadoopconf" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOROOT)
	/root/go/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOPATH)
package github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs: cannot find package "github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOROOT)
	/root/go/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOPATH)
package github.com/colinmarc/hdfs/v2/internal/rpc: cannot find package "github.com/colinmarc/hdfs/v2/internal/rpc" in any of:
	/usr/local/go/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOROOT)
	/root/go/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOPATH)
-----------------------------------------------------------------------------------

do you know how to solve this problem?
thanks

**Comment by colinmarc** [comment]
Hi @tenghuan,

Please update your go to 1.10.3. See #142 for more information.
