### ISSUE TITLE
fatal error: runtime: netpoll failed

### ISSUE THREAD

**Issue by qianfangyuan** [colinmarc/hdfs#147]
[root@selene24 data1]# /usr/local/hadoop/bin/hadoop  fs -ls hdfs://xxxxxxx:9000/
Found x items
drwxr-xr-x   - hadoop supergroup          0 2017-12-27 12:10 hdfs://xxxxxxx:9000/backup
drwxrwxrwx   - hadoop supergroup          0 2018-03-22 16:04 hdfs://xxxxxxx:9000/user
[root@selene24 data1]# ./hdfs  ls hdfs://xxxxxxx:9000/                          
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x8c328d, 0x17)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/runtime/panic.go:608 +0x72
runtime.netpoll(0x15538d1a51966c00, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/runtime/netpoll_epoll.go:75 +0x215
runtime.sysmon()
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/runtime/proc.go:4390 +0x41b
runtime.mstart1()
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/runtime/proc.go:1282 +0xe6
runtime.mstart()
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/runtime/proc.go:1248 +0x6e

goroutine 1 [select]:
net.(*Resolver).LookupIPAddr(0xc7e860, 0x940e60, 0xc00007a360, 0x7fff01baab50, 0x1c, 0x7fff01baab6d, 0x4, 0x2328, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0xc7e860, 0x940e60, 0xc00007a360, 0x8bbefb, 0x3, 0x7fff01baab50, 0x21, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0xc7e860, 0x940e60, 0xc00007a360, 0x8bc23b, 0x4, 0x8bbefb, 0x3, 0x7fff01baab50, 0x21, 0x0, ...)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0xc00007a300, 0x940e20, 0xc0000240e0, 0x8bbefb, 0x3, 0x7fff01baab50, 0x21, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/dial.go:384 +0x201
net.(*Dialer).DialContext-fm(0x940e20, 0xc0000240e0, 0x8bbefb, 0x3, 0x7fff01baab50, 0x21, 0xc7ed00, 0x18, 0x10, 0x10)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/main.go:221 +0x73
github.com/colinmarc/hdfs/v2/internal/rpc.(*NamenodeConnection).resolveConnection(0xc0000e69a0, 0x8bd4f5, 0x8)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/internal/rpc/namenode.go:145 +0x1bc
github.com/colinmarc/hdfs/v2/internal/rpc.NewNamenodeConnection(0xc000066f50, 0x1, 0x1, 0xc000024670, 0x4, 0xc000066f90, 0x0, 0x0, 0x0, 0xc7f800, ...)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/internal/rpc/namenode.go:117 +0x325
github.com/colinmarc/hdfs/v2.NewClient(0xc000066f50, 0x1, 0x1, 0xc000024670, 0x4, 0x0, 0xc000066f90, 0xc000066f90, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/client.go:132 +0x168
main.getClient(0x7fff01baab50, 0x21, 0x1, 0xc000066f40, 0x1)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/main.go:226 +0x30c
main.getClientAndExpandedPaths(0xc000066f40, 0x1, 0x1, 0xc000109e58, 0x7a9f45, 0xc0001565b0, 0xc000109e90, 0x7fff01baab46, 0x2)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/paths.go:55 +0x8c
main.ls(0xc00001e1a0, 0x1, 0x1, 0x0)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/ls.go:17 +0x68
main.main()
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/main.go:110 +0x2b5

goroutine 6 [runnable]:
net.getFields(0x0, 0x0, 0x23, 0xffffffffffffffff, 0x2)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/parse.go:121 +0x77
net.readHosts()
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/hosts.go:75 +0x205
net.lookupStaticHost(0x7fff01baab50, 0x1c, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/hosts.go:106 +0x87
net.goLookupIPFiles(0x7fff01baab50, 0x1c, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/dnsclient_unix.go:514 +0x4d
net.(*Resolver).goLookupIPCNAMEOrder(0xc7e860, 0x940de0, 0xc00002e300, 0x7fff01baab50, 0x1c, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/dnsclient_unix.go:535 +0x12f8
net.(*Resolver).lookupIP(0xc7e860, 0x940de0, 0xc00002e300, 0x7fff01baab50, 0x1c, 0x0, 0xc000001b00, 0xc00002e0c0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/lookup_unix.go:101 +0xd7
net.(*Resolver).lookupIP-fm(0x940de0, 0xc00002e300, 0x7fff01baab50, 0x1c, 0x42b282, 0x8, 0xc00002e0c0, 0x0, 0xc0000526a0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/lookup.go:207 +0x56
net.glob..func1(0x940de0, 0xc00002e300, 0xc000066fc0, 0x7fff01baab50, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/net/lookup.go:221 +0xd8
internal/singleflight.(*Group).doCall(0xc7e870, 0xc0000cc2d0, 0x7fff01baab50, 0x1c, 0xc000160330)
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
        /home/travis/.gimme/versions/go1.11beta2.linux.amd64/src/internal/singleflight/singleflight.go:88 +0x2a0

**Comment by colinmarc** [comment]
Hi there,

what OS are you on? Are you using the prebuilt releases or building your own binary?

**Comment by qianfangyuan** [comment]
centos7.1, use the prebuilt releases v2.0.0

**Comment by colinmarc** [comment]
@qianfangyuan can you try building from source and see if the problem persists? It should be fairly straightforward - install go and then `make`.

**Comment by colinmarc** [comment]
Hi @qianfangyuan, you might post on https://github.com/golang/go/issues/24980 - seems like it might be related. I'm going to close this since it seems like a general go issue and not an HDFS one, but I'm happy to discuss further if you like.

**Comment by qianfangyuan** [comment]
thanks
