### ISSUE TITLE
hdfs ls fails to work with SASL connect error

### ISSUE THREAD

**Issue by AnirudhVyas** [colinmarc/hdfs#148]
while doing hdfs ls / i get kerberos error 
```
Couldn't connect to namenode: no available namenodes: SASL handshake: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: TGS Exchange Error: failed to generate a new TGS_REQ < Encrypting_Error: error getting etype to encrypt authenticator: unknown or unsupported EType: 1
```

Any suggestions?

**Comment by AnirudhVyas** [comment]
this is my sample code - 
`
f, err := os.Create("ls.log")
	if err != nil {
		panic(err)
	}
	log.SetOutput(f)
	ccache, err := credentials.LoadCCache("/tmp/krb5cc_72438")
	log.Printf("ccache loaded : %+v\n", ccache)
	if err != nil {
		panic(err)
	}
	// krb "gopkg.in/jcmturner/gokrb5.v5/client"
	//cl := krb.NewClientWithPassword("USER_NAME", "REALM.COM", "PASSWORD")
	cl, err := krb.NewClientFromCCache(ccache)
	log.Printf("ccache loaded, client created as : %+v\n", cl)
	if err != nil {
		panic(err)
	}
	dialFunc := (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
		DualStack: true,
	}).DialContext
	options := hdfs.ClientOptions{
		Addresses:                    []string{"NN_HOST:NN_PORT"},
		NamenodeDialFunc:             dialFunc,
		DatanodeDialFunc:             dialFunc,
		KerberosClient:               &cl,
		KerberosServicePrincipleName: "krbtgt/WORKDAY.COM@WORKDAY.COM",
	}
	client, err := hdfs.NewClient(options)
	log.Printf("### ccache loaded, client created as : %+v\n", cl)
	if err != nil {
		panic(err)
	} else {
		files, e := client.ReadDir("/")
		if e != nil {
			panic(e)
		} else {
			var names []string
			for _, f := range files {
				log.Printf("@@@@@@@@@@@@ %+v", f)
				names = append(names, f.Name())
			}
			return names, nil
		}
	}
`

**Comment by mxk1235** [comment]
i had this error when the encoding type requested by the KDC was not present in the keytab.

**Comment by colinmarc** [comment]
Hi @AnirudhVyas, thanks for the report!

Can you confirm you have data privacy turned on, as in #145?

**Comment by AnirudhVyas** [comment]
Let me check and confirm. The error is slightly different in that case - in my case the more precise error is - 
```
failed to generate a new TGS_REQ < Encrypting_Error: error getting etype to encrypt authenticator: unknown or unsupported EType: 1
```
I did a bit of digging and reported this bug to [https://github.com/jcmturner/gokrb5/issues/202](gokrb5 kerberos bug)
I suspect - This has to do with EType 1 which as per gokrb5 codebase is DES CBC CRC which I do not find any implementation of, Our supported types are - 
```
default_tgs_enctypes = arcfour-hmac-md5 des-cbc-md5 des-cbc-crc des3-cbc-sha1
```
I think unfortunately none of these are implemented in gokrb5 library - unless I am missing something very basic. Unless we find a solution we could just implement looking at RFCs ... I think scope of those implementations isn't that much. I am not blocked by this at the moment as my fallback is scala hdfs client (basically java client) however it is damn slow, so I have to weave go routines to do what I intend to do to get the same effect unfortunately.

Let me know if you know anything better as well. I will report back on data privacy thing in a bit.

**Comment by AnirudhVyas** [comment]
> i had this error when the encoding type requested by the KDC was not present in the keytab.

I am not familiar with kerberos that much, I will read on it this weekend perhaps, could you tell me if Key distribution center encoding types are the same as whats present in /etc/krb5.conf file? For me yes the krb5 file doesn't have those that are supported, I could try adding what is supported and see if that flies... kinda shooting in dark without knowing much, so will first read and then try ... thanks for the response.

**Comment by mxk1235** [comment]
when you are generating the keytab, you can try `-crypto all` or `-crypto RC4-HMAC`
 option to which encryption types.
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/tsec_kerb_create_spn.html

good luck!

**Comment by colinmarc** [comment]
Hi @AnirudhVyas, any luck with this?
