### ISSUE TITLE
MkDirAll file already exists error.

### ISSUE THREAD

**Issue by sripathivenky** [colinmarc/hdfs#156]
@colinmarc  As per documentation

func (c *Client) MkdirAll(dirname string, perm os.FileMode) error

MkdirAll creates a directory for dirname, along with any necessary parents, and returns nil, or else returns an error. The permission bits perm are used for all directories that MkdirAll creates. **If dirname is already a directory, MkdirAll does nothing and returns nil.** 

But insted in Version 2.0.0 I am getting file already exists error.

I see that hdfs/mkdir.go 
MkDirAll calls mkdir method on line 21 that in return 
line 34: return &os.PathError{"mkdir", dirname, os.ErrExist} being sent back for

**Comment by colinmarc** [comment]
Hi @sripathivenky, 

There's a test for this already: https://github.com/colinmarc/hdfs/blob/c5e93df697d823976844a79ec9a70e51105b4639/mkdir_test.go#L68-L78

Are you sure the path doesn't exist as a file?

Going to close this, but feel free to let me know if I got something wrong.
