### ISSUE TITLE
is there some problem when use v1.1.3 to connect hadoop-2.6.5?

### ISSUE THREAD

**Issue by Constlin** [colinmarc/hdfs#166]
I use v1.1.3 to connect hdfs-2.6.5, but there will be an error when call 'hdfs.New', the error is that the client can't connect to the hdfs's Datanode.
client environment:
os: macOS 10.12.2
go: go1.10
colinmarc/hdfs: v1.1.3

server environment:
os: Linux version 3.10.0-327.28.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Aug 18 19:05:49 UTC 2016
hadoop: v2.6.5

**Comment by colinmarc** [comment]
What's the exact error? My guess is https://github.com/colinmarc/hdfs/pull/13, in which case downgrading to 1.1.2 should fix it. Or take a look at your DNS setup.

**Comment by colinmarc** [comment]
Going to close this, but feel free to let me know if that doesn't fix it.
