### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by JKeita** [colinmarc/hdfs#173]
vendor/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs/ClientDatanodeProtocol.pb.go:9:8: use of internal package github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common not allowed
vendor/github.com/colinmarc/hdfs/client.go:15:2: use of internal package github.com/colinmarc/hdfs/v2/internal/rpc not allowed

go version go1.11.4 linux/amd64

**Comment by zt706** [comment]
How to fix?

**Comment by saurabhsuniljain** [comment]
Getting the same issue again.

**Comment by colinmarc** [comment]
Are you using a third-party package manager? Are there a set of commands I can try to reproduce?

**Comment by Thea-R** [comment]
getting the same issue
go version go1.13.5 darwin/amd64

**Comment by Paraoia** [comment]
The same issue with govendor.
go version go1.12.9 darwin/amd64

command:
govendor init
govendor add +external
go run main.go

output:
vendor/github.com/colinmarc/hdfs/client.go:14:2: use of internal package github.com/colinmarc/hdfs/internal/protocol/hadoop_hdfs not allowed
vendor/github.com/colinmarc/hdfs/client.go:15:2: use of internal package github.com/colinmarc/hdfs/internal/rpc not allowed

**Comment by Paraoia** [comment]
Solved.

command:
git clone this repo.
git checkout v1.1.3
copy repo(v1.1.3) to vendor dir
