### ISSUE TITLE
Received unexpected error: dial tcp 127.0.0.1:9866: i/o timeout

### ISSUE THREAD

**Issue by qingfengshuixu** [colinmarc/hdfs#174]
When i run client_test.go,  TestCopyToRemote, it return err,  "dial tcp 127.0.0.1:9866: i/o timeout". but when i run the client_test.go in the linux system and  the hadoop run  in the same machine, it's ok, Why?

**Comment by colinmarc** [comment]
Hi @qingfengshuixu, not sure; there could be many reasons for a timeout. I'm going to close this, but feel free to chime in with more information.
