### ISSUE TITLE
kerberos enabled, but kerberos client is missing credentials

### ISSUE THREAD

**Issue by atdevp** [colinmarc/hdfs#175]
hello:

I can't connect hdfs. my program:

package main

import (
	"log"

	"github.com/colinmarc/hdfs"
	"github.com/colinmarc/hdfs/hadoopconf"
	krbclient "gopkg.in/jcmturner/gokrb5.v5/client"
	keytab "gopkg.in/jcmturner/gokrb5.v5/keytab"
)

func init() {
	log.SetFlags(log.Ldate | log.Ltime | log.Llongfile)
}

func getkrbClient() (krbclient.Client, error) {

	kt, err := keytab.Load("/opt/userdata/keytab/mrddev.keytab")
	if err != nil {
		log.Printf("[E] keytab init failed. %s", err.Error())
		return krbclient.Client{}, err
	}

	cli := krbclient.NewClientWithKeytab("mrddev", "OTOCYON.COM", kt)
	return cli, nil

}

func main() {

	dir := "/user/myname/test"

	hadoopConf, err := hadoopconf.Load("/etc/hadoop/conf")
	if err != nil {
		log.Printf("hadoopConf init failed. %s", err.Error())
		return
	}

	clientOptions := hdfs.ClientOptionsFromConf(hadoopConf)

	log.Println(clientOptions.Addresses, clientOptions.KerberosServicePrincipleName, clientOptions.User)

	c, err := hdfs.NewClient(clientOptions)

	if err != nil {
		log.Printf("[E] hdfs init new clint failed. %s", err.Error())
		return
	}

	f, err := c.Stat(dir)
	if err != nil {
		log.Printf("client  stat %s error: %s", dir, err.Error())
		return
	}
	ok := f.IsDir()
	if ok {
		log.Printf("%s is directory", dir)
		return
	}
	log.Printf("%s is not director", dir)
	return

}

**Comment by zhjianxia** [comment]
getkrbClient Should be modified as below:

func getkrbClient() (*krbclient.Client, error) {
	configPath := os.Getenv("KRB5_CONFIG")
	if configPath == "" {
		configPath = "/etc/krb5.conf"
	}
	log.Println(configPath)
	cfg, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}

	kt, err := keytab.Load("/etc/security/keytabs/test0424.keytab")
	log.Println("keytab loaded ok.")
	if err != nil {
		log.Printf("[E] keytab init failed. %s", err.Error())
		return nil, err
	}

	cli := krbclient.NewClientWithKeytab("test0424", "BCHKDC", kt)
	log.Println("NewClientWithKeytab ok.")
	cli.WithConfig(cfg)

	// Log in the client
	err = cli.Login()
	if err != nil {
		log.Printf("Error on AS_REQ: %v\n", err)
	}

	return cli.WithConfig(cfg), nil
}


Also at main function, below should be added to call the getkrbClient function:
clientOptions := hdfs.ClientOptionsFromConf(hadoopConf)

	if clientOptions.KerberosClient != nil {
		// Replace with a valid credentialed client.
		clientOptions.KerberosClient, err = getkrbClient()
		if err != nil {
			log.Println("failed to call getkrbClient:", err)
		}
	}
