### ISSUE TITLE
Need to trigger lease recovery manually

### ISSUE THREAD

**Issue by systm32** [colinmarc/hdfs#182]
I am seeing the issue where sometimes the file doesn't get written to datanode properly if written using go hdfs client. But if I manual trigger recover lease on that file the file is available.
FYI file is not large it is approx 5-6 MB. I'm seeing this issue rarely. Also, I am using the CopyToRemove API to write the file.
Any idea what could be the possible reason for this?

**Comment by colinmarc** [comment]
Hi @systm32, 

Are you only using `CopyToRemote`? I would expect to see that issue if you e.g. forgot to call `Close` on the FileWriter.

**Comment by colinmarc** [comment]
Going to close, since I haven't heard from you in a while.
