### ISSUE TITLE
Couldn't connect to namenode: no available namenodes: SASL handshake: [Root cause: KDC_Error] KDC_Error: TGS Exchange Error: kerberos error response from KDC: KRB Error: (7) KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database - UNKNOWN_SERVER

### ISSUE THREAD

**Issue by hobinyoon** [colinmarc/hdfs#183]
Hi, can I get some eyes on the following error? I am trying to use the Go client with Kerberos. It's working with Java client. I must be missing something.

client:~/go/colinmarc/hdfs# klist
  Ticket cache: FILE:/tmp/krb5cc_0
  Default principal: user1/hdfs@LOCAL.ABCINTERNAL.COM

  Valid starting     Expires            Service principal
  04/25/19 21:37:18  04/26/19 21:37:18  krbtgt/LOCAL.ABCINTERNAL.COM@LOCAL.ABCINTERNAL.COM

client:~/go/colinmarc/hdfs# hdfs dfs -ls /
  2019-04-25 22:01:32,041 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
  Found 1 items
  drwxr-xr-x   - user1 hdfs-admins          0 2019-04-19 17:43 /test

client:~/go/colinmarc/hdfs# ./hdfs ls /test
  Couldn't connect to namenode: no available namenodes: SASL handshake: [Root cause: KDC_Error] KDC_Error: TGS Exchange Error: kerberos error response from KDC: KRB Error: (7) KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database - UNKNOWN_SERVER

I tried to follow some of the advices here but with no luck.
  https://stackoverflow.com/questions/13850252/cannot-get-kerberos-service-ticket-krbexception-server-not-found-in-kerberos-d

**Comment by colinmarc** [comment]
Hi @hobinyoon, I'm not really sure, but this seems like an issue with your krb configuration. As this is pretty old, I'm going to close it, but feel free to chime in with more information.
