### ISSUE TITLE
support wildcard character unfriendly

### ISSUE THREAD

**Issue by xzy256** [colinmarc/hdfs#185]
Gohdfs support wildcard character unfriendly.
When executing `./hdfs ls /tmp/test/*/*.txt` ,  i get `readdir /tmp/test/2018/1.txt: the file is not a directory` error.
However executing `./hdfs ls /tmp/test/*`, it can run and display all files below dirs except files below `/tmp/test`.  Amazing. Is it a bug?
output as follow:
<pre>
#./hdfs ls /tmp/test/* 
/tmp/test/2018/:
1.txt
sync_hotword_utf8_adjust2019052012.txt
/tmp/test/2019/:
1.txt
2.txt
LICENSE.txt
foo.txt
/tmp/test/hdfs.go
/tmp/test/hdfs.go/:
readdir /tmp/test/hdfs.go: the file is not a directory
</pre>
path tree:
/tmp/test
├── 2018
│   ├── 1.txt
│   └── sync_hotword_utf8_adjust2019052012.txt
├── 2019
│   ├── 1.txt
│   ├── 2.txt
│   ├── foo.txt
│   └── LICENSE.txt
└── hdfs.go

**Comment by colinmarc** [comment]
Hi @xzy256,

This does appear to be a bug, or at least weird. `ls` is interpreting `/tmp/test/hdfs.go` as a directory.

**Comment by xzy256** [comment]
It's really  weird.  Looking forward to fixing it

**Comment by xzy256** [comment]
So sorry @colinmarc . The bug is introduced by me when developed for supportting `hdfs://` and `viewfs` filesystem. I have fixed it. Thanks for your patience.
