### ISSUE TITLE
Add ability to copy file from one cluster to another

### ISSUE THREAD

**Issue by mudejar** [colinmarc/hdfs#186]
It would be nice if this library allowed for copying data from one cluster to another. Basically being able to use the MapReduce’s distributed copy to move data with a MapReduce job, that is something that can be done normally with a command such as the following:
```hadoop -distcp hdfs://namenode:8020/user/thenson \ hdfs://newNameNode:8020/user/thenson```

Does this library already have the capability of performing the same function as that command?

**Comment by colinmarc** [comment]
Hi @mudejar,

As I understand it, distcp copies the data through the local machine - there's no api for copying data directly. So there's no way to implement that in the library in a way that doesn't hide performance issues and perform confusingly. Thanks for the suggestion, though!
