### ISSUE TITLE
no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)

### ISSUE THREAD

**Issue by Mengqi777** [colinmarc/hdfs#190]
I got a SaslException like :  `no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)`

my code is :

`
func getkrbClient() (*krbclient.Client, error) {

	configPath := os.Getenv("KRB5_CONFIG")
	if configPath == "" {
		configPath = "/etc/krb5.conf"
	}

	cfg, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}
	log.Println(cfg.Realms[0].DefaultDomain)
	log.Println(cfg.Realms[0].Realm)

	ccachePath := os.Getenv("KRB5CCNAME")
	log.Println("get ccachePath %s",ccachePath)
	if strings.Contains(ccachePath, ":") {
		if strings.HasPrefix(ccachePath, "FILE:") {
			ccachePath = strings.SplitN(ccachePath, ":", 2)[1]
		} else {
			return nil, fmt.Errorf("unusable ccache: %s", ccachePath)
		}
		log.Println(" ccachePath contains :")
	} else if ccachePath == "" {
		u, err := user.Current()
		if err != nil {
			return nil, err
		}
		ccachePath = fmt.Sprintf("/tmp/krb5cc_%s", u.Uid)
		log.Println("tmp krb5cc ccachepath %s",ccachePath)
	}
	ccache, err := credentials.LoadCCache(ccachePath)
	if err != nil {
		return nil, err
	}
	client, err := krbclient.NewClientFromCCache(ccache)
	if err != nil {
		return nil, err
	}
	kt, err := keytab.Load("/tmp/slave.keytab")
	client.WithKeytab(kt)
	err = client.Login()
	if err != nil {
		log.Printf("Error on AS_REQ: %v\n", err)
	}
	return client.WithConfig(cfg), nil
}

func main() {
	dir := "/user/myname/test"
	hadoopConf, err := hadoopconf.Load("/etc/hadoop/conf")
	if err != nil {
		log.Printf("hadoopConf init failed. %s", err.Error())
		return
	}
	clientOptions := hdfs.ClientOptionsFromConf(hadoopConf)
	if clientOptions.KerberosClient != nil {
		// Replace with a valid credentialed client.
		clientOptions.KerberosClient, err = getkrbClient()
		if err != nil {
			log.Println("failed to call getkrbClient:", err)
		}
	}
	clientOptions.KerberosServicePrincipleName=clientOptions.KerberosClient.Credentials.CName.GetPrincipalNameString()
	c, err := hdfs.NewClient(clientOptions)
	if err != nil {
		log.Println(err)
		return
	}
	f, err := c.Stat(dir)
	if err != nil {
		log.Printf("client  stat %s error: %s", dir, err.Error())
		return
	}
	ok := f.IsDir()
	if ok {
		log.Printf("%s is directory", dir)
		return
	}
	log.Printf("%s is not director", dir)
	return
}
`

**Comment by torubylist** [comment]
> I got a SaslException like : `no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)`
> 
> my code is :
> 
> `
> func getkrbClient() (*krbclient.Client, error) {
> 
> ```
> configPath := os.Getenv("KRB5_CONFIG")
> if configPath == "" {
> 	configPath = "/etc/krb5.conf"
> }
> 
> cfg, err := config.Load(configPath)
> if err != nil {
> 	return nil, err
> }
> log.Println(cfg.Realms[0].DefaultDomain)
> log.Println(cfg.Realms[0].Realm)
> 
> ccachePath := os.Getenv("KRB5CCNAME")
> log.Println("get ccachePath %s",ccachePath)
> if strings.Contains(ccachePath, ":") {
> 	if strings.HasPrefix(ccachePath, "FILE:") {
> 		ccachePath = strings.SplitN(ccachePath, ":", 2)[1]
> 	} else {
> 		return nil, fmt.Errorf("unusable ccache: %s", ccachePath)
> 	}
> 	log.Println(" ccachePath contains :")
> } else if ccachePath == "" {
> 	u, err := user.Current()
> 	if err != nil {
> 		return nil, err
> 	}
> 	ccachePath = fmt.Sprintf("/tmp/krb5cc_%s", u.Uid)
> 	log.Println("tmp krb5cc ccachepath %s",ccachePath)
> }
> ccache, err := credentials.LoadCCache(ccachePath)
> if err != nil {
> 	return nil, err
> }
> client, err := krbclient.NewClientFromCCache(ccache)
> if err != nil {
> 	return nil, err
> }
> kt, err := keytab.Load("/tmp/slave.keytab")
> client.WithKeytab(kt)
> err = client.Login()
> if err != nil {
> 	log.Printf("Error on AS_REQ: %v\n", err)
> }
> return client.WithConfig(cfg), nil
> ```
> 
> }
> 
> func main() {
> dir := "/user/myname/test"
> hadoopConf, err := hadoopconf.Load("/etc/hadoop/conf")
> if err != nil {
> log.Printf("hadoopConf init failed. %s", err.Error())
> return
> }
> clientOptions := hdfs.ClientOptionsFromConf(hadoopConf)
> if clientOptions.KerberosClient != nil {
> // Replace with a valid credentialed client.
> clientOptions.KerberosClient, err = getkrbClient()
> if err != nil {
> log.Println("failed to call getkrbClient:", err)
> }
> }
> clientOptions.KerberosServicePrincipleName=clientOptions.KerberosClient.Credentials.CName.GetPrincipalNameString()
> c, err := hdfs.NewClient(clientOptions)
> if err != nil {
> log.Println(err)
> return
> }
> f, err := c.Stat(dir)
> if err != nil {
> log.Printf("client stat %s error: %s", dir, err.Error())
> return
> }
> ok := f.IsDir()
> if ok {
> log.Printf("%s is directory", dir)
> return
> }
> log.Printf("%s is not director", dir)
> return
> }
> `

大佬。你这个问题解决了么？我碰到相同的问题了。

**Comment by Mengqi777** [comment]
这个是gohdfs的吧，我放弃了，没弄过这个了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yongpingzhao <notifications@github.com>
发送时间: Sunday, June 14, 2020 5:01:50 PM
收件人: colinmarc/hdfs <hdfs@noreply.github.com>
抄送: 孟琦 <memgqi@live.cn>; State change <state_change@noreply.github.com>
主题: Re: [colinmarc/hdfs] no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException) (#190)


I got a SaslException like : no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)

my code is :

`
func getkrbClient() (*krbclient.Client, error) {

configPath := os.Getenv("KRB5_CONFIG")

if configPath == "" {

        configPath = "/etc/krb5.conf"

}



cfg, err := config.Load(configPath)

if err != nil {

        return nil, err

}

log.Println(cfg.Realms[0].DefaultDomain)

log.Println(cfg.Realms[0].Realm)



ccachePath := os.Getenv("KRB5CCNAME")

log.Println("get ccachePath %s",ccachePath)

if strings.Contains(ccachePath, ":") {

        if strings.HasPrefix(ccachePath, "FILE:") {

                ccachePath = strings.SplitN(ccachePath, ":", 2)[1]

        } else {

                return nil, fmt.Errorf("unusable ccache: %s", ccachePath)

        }

        log.Println(" ccachePath contains :")

} else if ccachePath == "" {

        u, err := user.Current()

        if err != nil {

                return nil, err

        }

        ccachePath = fmt.Sprintf("/tmp/krb5cc_%s", u.Uid)

        log.Println("tmp krb5cc ccachepath %s",ccachePath)

}

ccache, err := credentials.LoadCCache(ccachePath)

if err != nil {

        return nil, err

}

client, err := krbclient.NewClientFromCCache(ccache)

if err != nil {

        return nil, err

}

kt, err := keytab.Load("/tmp/slave.keytab")

client.WithKeytab(kt)

err = client.Login()

if err != nil {

        log.Printf("Error on AS_REQ: %v\n", err)

}

return client.WithConfig(cfg), nil



}

func main() {
dir := "/user/myname/test"
hadoopConf, err := hadoopconf.Load("/etc/hadoop/conf")
if err != nil {
log.Printf("hadoopConf init failed. %s", err.Error())
return
}
clientOptions := hdfs.ClientOptionsFromConf(hadoopConf)
if clientOptions.KerberosClient != nil {
// Replace with a valid credentialed client.
clientOptions.KerberosClient, err = getkrbClient()
if err != nil {
log.Println("failed to call getkrbClient:", err)
}
}
clientOptions.KerberosServicePrincipleName=clientOptions.KerberosClient.Credentials.CName.GetPrincipalNameString()
c, err := hdfs.NewClient(clientOptions)
if err != nil {
log.Println(err)
return
}
f, err := c.Stat(dir)
if err != nil {
log.Printf("client stat %s error: %s", dir, err.Error())
return
}
ok := f.IsDir()
if ok {
log.Printf("%s is directory", dir)
return
}
log.Printf("%s is not director", dir)
return
}
`

大佬。你这个问题解决了么？我碰到相同的问题了。

―

**Comment by zmloong** [comment]
这个问题有解决方案吗？我碰到相同的问题了
