### ISSUE TITLE
go module hadoopconf

### ISSUE THREAD

**Issue by AnirudhVyas** [colinmarc/hdfs#197]
I am getting this issue - 
```go: finding github.com/colinmarc/hdfs/hadoopconf latest
HDFSUtil.go:13:2: unknown import path "github.com/colinmarc/hdfs/hadoopconf": cannot find module providing package github.com/colinmarc/hdfs/hadoopconf
```
I use go version go1.12.7 darwin/amd64 and it seems like hdfs hadoop conf is playing havoc with our build which uses go mod extensively.

**Comment by AnirudhVyas** [comment]
at the moment I fixed it by cloning the repo and adding a go.mod by myself on hadoopconf, please do it for the repo as well.

**Comment by colinmarc** [comment]
Hm, that shouldn't be necessary. How are you including the project?
