### ISSUE TITLE
Update go mod file version

### ISSUE THREAD

**Issue by movsb** [colinmarc/hdfs#200]
https://github.com/colinmarc/hdfs/blob/6f7e441ec688730014b4ca08657db358d7a45b87/go.mod#L1

Latest Go build keeps reporting that your project go.mod needs updating.

```
go run main.go 
go: finding github.com/colinmarc/hdfs v2.0.0
go: github.com/colinmarc/hdfs@v0.0.0-20180805214818-fd1e410ff7bf: go.mod has post-v0 module path "github.com/colinmarc/hdfs/v2" at revision fd1e410ff7bf
go: error loading module requirements
```

**Comment by colinmarc** [comment]
Hi @movsb, I'm not sure how you're getting this error. I'm going to close, but feel free to reopen if you have more details on how to reproduce.
