### ISSUE TITLE
wrong Token ID 

### ISSUE THREAD

**Issue by r2dedios** [colinmarc/hdfs#209]
Hi,

I'm trying to use this library to get HDFS directories usage from a HDFS Cluster securized with Kerberos.

Kerberos is working and the user, keytab i am using are correct and I can do "kinit" successfully.

But with my Go code, when I create the HDFS client configured for Kerberos it fails.

This is how i create the client.

    // Loading Keytab File
    kt, err := keytab.Load(config.KerberosKeytabPath)
    if err != nil {
      log.Err_msg(err.Error())
      return false
    }

    // Creating Kerberos Client with the Keytab
    krb5Client := krb.NewClientWithKeytab(
      getUserFromPrincipal(config.KerberosPrincipal),
      getRealmFromPrincipal(config.KerberosPrincipal),
      kt)

    // Loading Kerberos client configuration
    krb5Client.LoadConfig("/etc/krb5.conf")

    // Kerberos Login
    err = krb5Client.Login()
    if err != nil {
      log.Err_msg(err.Error())
      return false
    }

    options := hdfs.ClientOptions{
      Addresses: []string{fmt.Sprintf("%s:%s", config.Host, config.Port)},
      NamenodeDialFunc: nil,
      DatanodeDialFunc: nil,
      KerberosClient: &krb5Client,
      KerberosServicePrincipleName: "hdfs/node.domain",
    }

    // Creating HDFS Client configured with Kerberos
    client, err = hdfs.NewClient(options)
    if err != nil {
      log.Err_msg(err.Error())
      return false
    }

And this is the error I get in the `hdfs.NewClient(options)` function

    no available namenodes: SASL handshake: wrong Token ID. Expected 0504, was 6030

I don't know if is a problem in my code or a bug in this library.

Thanks

**Comment by colinmarc** [comment]
Hi, what're the values of `hadoop.rpc.protection` and `dfs.encrypt.data.transfer` in your config?

Also, you might check out [ClientOptionsFromConf](https://godoc.org/github.com/colinmarc/hdfs#ClientOptionsFromConf).

I suspect this is a duplicate of #145.

**Comment by r2dedios** [comment]
Hi Colin,

I have fix the error. I'm using your library to access to a HDFS securized with Kerberos. The problem was with my Kerberos Server configuration. My keytab didn't include the password with a valid encryption type for Kerberos.

When I add the properly enctription types to KDC server your library work perfectly.

Thanks for you quick response. If I can help you with something just tell me. I would like to collaborate in this repo.

Thanks again.

**Comment by wolfedale** [comment]
I'm getting the same error. Not sure what I'm doing wrong. Credentials looks ok to me.

`$ export HADOOP_CONF_DIR="/etc/hadoop/conf/"
$ hdfs dfs -ls
Found 1 items
drwxrwxr-x   - ek-hadoop-ingestion ek-hadoop-ro          0 2020-02-13 21:00 .Trash

$ ./hdfs-go ls
Couldn't connect to namenode: no available namenodes: SASL handshake: wrong Token ID. Expected 0504, was 6030`

The same if I setup all those settings in the lib:

`func (h *Hadoop) setClient(conn string) error {

	kt, err := config.Load(krb5.conf)
	if err != nil {
		return err
	}

	ktFromFile, err := keytab.Load(keytab)
	if err != nil {
		return err
	}

	krb5Client := client.NewClientWithKeytab(user, "FOO.SO", ktFromFile, kt)

	err = krb5Client.Login()
	if err != nil {
		return err
	}

	options := hdfs.ClientOptions{
		Addresses:                    []string{fmt.Sprintf(node)},
		NamenodeDialFunc:             nil,
		DatanodeDialFunc:             nil,
		KerberosClient:               krb5Client,
		KerberosServicePrincipleName: principleName,
	}

	client, err := hdfs.NewClient(options)
	if err != nil {
		return err
	}
	h.Client = client
	return nil
}`

What can be wrong? The standard `hdfs` is working fine for me.

**Comment by Yi-Hunter** [comment]
- Same question, and i have more details.
- My kerberos is useing **rc4-hmac** as enctype, and my hdfs conf is below.
- I know the encrypt algorithm not match, but i don't know how to modify my golang code.
- I have no permission to change kerberos and hdfs conf.

- core-site.xml

```xml
  <property>
    <name>hadoop.security.authentication</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hadoop.security.authorization</name>
    <value>true</value>
  </property>
  <property>
    <name>hadoop.rpc.protection</name>
    <value>authentication</value>
  </property>
  <property>
    <name>hadoop.security.auth_to_local</name>
    <value>DEFAULT</value>
  </property>
```

- hdfs-site.xml

```xml
  <property>
    <name>dfs.encrypt.data.transfer.algorithm</name>
    <value>3des</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.suites</name>
    <value>AES/CTR/NoPadding</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.key.bitlength</name>
    <value>256</value>
  </property>
```
