### ISSUE TITLE
Write HDFS data Socket time out (2)

### ISSUE THREAD

**Issue by alexryndin** [colinmarc/hdfs#210]
Hello! I've checked out your latest commits and it seems they contain some regression changes. There were some issues with data not being flushed to datanodes if block size is too small (https://github.com/colinmarc/hdfs/issues/135) and problems with Namenode lease not being updated (https://github.com/colinmarc/hdfs/issues/135). Despite these issues look to be already fixed, I've got familiar issue with latest (https://github.com/colinmarc/hdfs/commit/7eabc3a9c0e7e8a08f8d03a161cdb3309e04c299) commit build. A command I used to test your library was `cat /dev/urandom | pv --rate-limit=$BLOCK_SIZE  | HADOOP_CONF_DIR=/etc/hadoop/conf | ./hdfs put /dev/stdin /tmp/test`. Regardless of $BLOCK_SIZE, after of 1 hour of data loading I get `write: broken pipe` and datanode complaining following:
 ```2019-11-26 14:54:15,470 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Exception for BP-1891900421-10.123.0.30-1410884922197:blk_3907796936_1102775082918
java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connected local=/10.123.1.41:1004 remote=/10.123.0.11:41632]. 300000 millis timeout left.
```

**Comment by colinmarc** [comment]
Thanks - I'm embarrassed that this was such an obvious bug/fix. Should be fixed in 1cf907da71b60951ec9d18dfd04d10c6a66bd197.
