### ISSUE TITLE
Instructions for building release package

### ISSUE THREAD

**Issue by dlamblin** [colinmarc/hdfs#213]
Thanks for the nice tool;
Since you're not building darwin packages any longer, I'm curious what the steps are to building one from the tagged version repo. In my 1.12 version of go it looks like `go get github.com/colinmarc/hdfs.git` has changed syntax somewhere.

**Comment by dlamblin** [comment]
Actually it looks like the following works fine:
```
go get github.com/colinmarc/hdfs/cmd/hdfs
go install github.com/colinmarc/hdfs/cmd/hdfs
```
And then updating the bashrc to include `$GOPATH/bin` in `$PATH` and sourcing `$GOPATH/src/github.com/colinmarc/hdfs/cmd/hdfs/bash_completion`
It may help others to mention it under **installing**.

**Comment by colinmarc** [comment]
I'm surprised the first one ever worked, actually. I'm going to close this since it sounds like it worked out for you.
