### ISSUE TITLE
"broken pipe" error

### ISSUE THREAD

**Issue by wangkuiyi** [colinmarc/hdfs#22]
Is there a minimum supported Hadoop version here? When I run on my CentOS 6.3 Hadoop 1.0.3 pseudo distributed mode, `hdfs` gives the following error:
``` 
$ HADOOP_NAMENODE=127.0.0.1:9000 hdfs ls /
stat /: write tcp 127.0.0.1:33202->127.0.0.1:9000: write: broken pipe
```
or
```
$ HADOOP_NAMENODE=localhost:9000 hdfs ls /
stat /: EOF
```
However, both `hadoop dfs -ls hdfs://localhost:9000/` and `hadoop dfs -ls hdfs://127.0.0.1:9000/` work.

**Comment by colinmarc** [comment]
Unfortunately, yeah, this cilent only supports 2.x HDFS clusters. I thought I had a note in the README to that effect, but I guess not!

**Comment by colinmarc** [comment]
Ok, added some words to the README. Thanks for bringing this up.
