### ISSUE TITLE
checksum function support

### ISSUE THREAD

**Issue by flashpixx** [colinmarc/hdfs#224]
Is it possible to add the [checksum](http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html#checksum) to the library?

**Comment by colinmarc** [comment]
Hi @flashpixx,

It already exists: [here](https://godoc.org/github.com/colinmarc/hdfs#FileReader.Checksum) is the library support and [here](https://github.com/colinmarc/hdfs/blob/master/cmd/hdfs/test/checksum.bats) are the tests for the commandline client.
