### ISSUE TITLE
whether the library support for HA

### ISSUE THREAD

**Issue by vivounicorn** [colinmarc/hdfs#23]
Hey @colinmarc 
    Thank you for your great library, our hadoop cluster using HA, when i use client like this:
client, err := hdfs.NewForUser("AutoCluster:8020", "user")

the error is:
dial tcp 220.194.103.40:8020: getsockopt: connection timed out

please help me.

**Comment by snnn** [comment]
I have the same question

**Comment by colinmarc** [comment]
Hi @vivounicorn @snnn, it sounds plausible that I'd need to build that out. PRs welcome! Otherwise I'll take a look when I get a chance.

**Comment by colinmarc** [comment]
@vivounicorn just spent a bit of time poking at this. What is `AutoCluster:8020`? One of the namenodes? the leader?

**Comment by sediah** [comment]
@colinmarc I'm using HA with CDH 5.x. Feel free to integrate following codes as you wish.
https://github.com/sediah/hdfs_ha

**Comment by colinmarc** [comment]
@sediah Oh, awesome. Thanks - I'll take a look!

**Comment by vivounicorn** [comment]
@colinmarc tks
