### ISSUE TITLE
Support for client side configs

### ISSUE THREAD

**Issue by visrajan** [colinmarc/hdfs#230]
Would like to have support for client side configs like the following parameters. This will be used for native client

dfs.client.block.write.replace-datanode-on-failure.policy
dfs.client.block.write.replace-datanode-on-failure.enable
dfs.client.block.write.retries

**Comment by visrajan** [comment]
@colinmarc  could you help me with this client side setting.

**Comment by colinmarc** [comment]
Hi @visrajan, 

Datanode failover in HDFS is extremely client-heavy, and the java implementation is more or less impossible to copy. So at the moment, there are no plans to add this functionality. You can see more about the issue here: #86.

Thanks for writing in!
