### ISSUE TITLE
no available namenodes: write tcp 172.17.0.3:39820->172.16.21.11:8020: write: broken pipe

### ISSUE THREAD

**Issue by yuyang199226** [colinmarc/hdfs#231]
err = hdfsClient.CopyToLocal("/prod/customer/CTF/chongqing/drc/tracking/online/20200528/nppv3.1.3/ppb/none_1.pb", "1.pb")
    if err != nil {
                log.Fatal(err)
    }

**Comment by Yichkhun** [comment]
I also met this problem, and would like to ask how to solve it finally.
