### ISSUE TITLE
namenode channel should be closed for once

### ISSUE THREAD

**Issue by TWL007** [colinmarc/hdfs#237]
https://github.com/colinmarc/hdfs/blob/cd715bff28aefb46a4e1e24c03c49f9a874818eb/internal/rpc/namenode.go#L302-L315

We shoud make sure channel will be closed for once to avoid panic:
`panic: close of closed channel [recovered]
	panic: close of closed channel `

**Comment by colinmarc** [comment]
See my comment on #241.
