### ISSUE TITLE
error:dial tcp: lookup tdw-xxx on xxx:53: no such host

### ISSUE THREAD

**Issue by hjl0508** [colinmarc/hdfs#240]
there 10 file in the hdfs。I get all file names in a dir. and the loop to read every file.
in normal it is ok to read all file .but some times it will get a error like :"dial tcp: lookup tdw-xxx on 127.0.0.1:53: no such host "
open is ok , ioutil.ReadAll(file) get the error . 
it is always ok in read the first file ,but in other file maybe part-002 or part-003 will get the error.
do anyone know how to fix this
the code like next
```go
for _, fileName := range fileNames {
		if !strings.HasPrefix(fileName, "part-") {
			continue
		}
		fileName = fmt.Sprintf("%s/%s/complex/intent_filter_new/%s", preDir, getDate(), fileName)
		log.Infof("filename:%s", fileName)
		file, err := fileClient.client.Open(fileName)
		if err != nil {
			return fmt.Errorf("open file:%s,error:%s", fileName, err)
		}

		bytesResult, err := ioutil.ReadAll(file)
		if err != nil {
			log.Infof("result:%v", string(bytesResult))
			return fmt.Errorf("read file:%s,error:%s", fileName, err) 
		}
}
```

**Comment by coquebg** [comment]
The error `dial tcp: lookup tdw-xxx on 127.0.0.1:53` usually means DNS resolution problem.
Do you use some DNS caching? (dnsmasq/bind) ?
