### ISSUE TITLE
hdfs get /xxx/x\* error，panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by midaug** [colinmarc/hdfs#244]
colinmarc/hdfs  version v2.1.1

execute  hdfs get /xxx/records/201910\* ./backup/xxx/records/201910
error info：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8243ed]

goroutine 1 [running]:
main.get.func1(0x7ffe3cc99714, 0x1c, 0x0, 0x0, 0x9dfda0, 0xc00012c960, 0xc000182230, 0xc0000950d0)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/get.go:44 +0xdd
github.com/colinmarc/hdfs/v2.(*Client).walk(0xc000182230, 0x7ffe3cc99714, 0x1c, 0xc000149e48, 0x0, 0x1)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/walk.go:25 +0xb0
github.com/colinmarc/hdfs/v2.(*Client).Walk(...)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/walk.go:15
main.get(0xc0000b2020, 0x2, 0x2)
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/get.go:41 +0x262
main.main()
        /home/travis/gopath/src/github.com/colinmarc/hdfs/cmd/hdfs/main.go:140 +0x62e

-------------------------
Non-fuzzy match is ok
E.g： hdfs get /xxx/records/20191001 ./backup/xxx/records/20191001

-------------------------
ls Use fuzzy matching is ok
E.g：hdfs ls /xxx/records/201910*
E.g：hdfs ls /xxx/records/201910\*

**Comment by colinmarc** [comment]
Hi @midaug,

I'm not sure what the issue is, here. I think I have a fix, which I will push in the meantime, but I'm having trouble constructing a test case to prevent regressions in the future. Could you open a PR with one, or at least describe the directory structure that leads to the issue described?

Thanks,
Colin
