### ISSUE TITLE
checksum error not propagate to upper function calls

### ISSUE THREAD

**Issue by bbiao** [colinmarc/hdfs#275]
In the code ( as in https://github.com/colinmarc/hdfs/blob/f2f512db170db82ad41590c4ba3b7718b13317d2/internal/transfer/block_read_stream.go#L72)

```
		err = s.validateChecksum(s.chunk.Bytes())
		if err != nil {
			return 0, nil
		}
```

If the validateChecksum return an err, it will just return 0, nil.

And in the following code (https://github.com/colinmarc/hdfs/blob/f2f512db170db82ad41590c4ba3b7718b13317d2/internal/transfer/block_reader.go#L95)

```
		n, err := br.stream.Read(b)
		br.Offset += int64(n)
		if err != nil && err != io.EOF {
			br.stream = nil
			br.datanodes.recordFailure(err)
			if n > 0 {
				return n, nil
			}

			continue
		}
```

There is a chance for the br.stream.Read return n > 0 and err = errInvalidChecksum, so the whole call will return n, nil

Is these a feature or a bug?

**Comment by colinmarc** [comment]
HI @bbiao,

The first is a bug, which I'll push a fix for shortly. The second is intended - the comment above the section you pasted explains that an error with a partial read is not cause for returning an error from `Read` (although the current stream is marked failed and closed). Instead, the next call to `Read` will fail over to the next datanode.

Note that in case of a checksum error, none of the bad data is returned, so `n` will be 0 in that case, and the failover and retry will happen immediately.
