### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by moredure** [colinmarc/hdfs#279]
Please check @colinmarc 
https://github.com/colinmarc/hdfs/pull/278 reduce allocations for header write
https://github.com/colinmarc/hdfs/pull/277 reduce allocation for outboundPacket
https://github.com/colinmarc/hdfs/pull/276 use only seqno instead of full outboundPacket in channel

**Comment by moredure** [comment]
@colinmarc

**Comment by colinmarc** [comment]
Addressed each PR individually. Thanks!
