### ISSUE TITLE
TCP connection to data nodes are actively leaked when Seek() or ReadAt() is used

### ISSUE THREAD

**Issue by vlivan-microsoft** [colinmarc/hdfs#28]
*Symphom:* "too many open files" error
*Repro Steps:* open large file and do a bunch of ReadAt() at random positions in a loop
*Details:* block reader isn't closed properly, so active TCP connections might grow with the high rate. Go garbage collector doesn't "feel" memory pressure - so it isn't cleaning them up on time leading to quick exhausting of available fds.

**Comment by vlivan-microsoft** [comment]
Fix: https://github.com/colinmarc/hdfs/pull/29

**Comment by colinmarc** [comment]
Fixed in #29.
