### ISSUE TITLE
no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)

### ISSUE THREAD

**Issue by zmloong** [colinmarc/hdfs#291]
This mistake has been mentioned before and has been closed. Has it been solved?

func getConnectKerberos(addr []string, username string) (*hdfs.Client, error) {

	hcf, err := hadoopconf.Load("./conf")
	if err != nil {
		fmt.Println(err)
	}
	options := hdfs.ClientOptionsFromConf(hcf)

	fmt.Println(options)
	//*导入kerberos配置
	var (
		ktp                  = "./conf/tujl.keytab"
		cfp                  = "./conf/krb5.conf"
		servicePrincipleName = "zml"
		uname                = "zml"
		realm                = "hadop"
	)

	kt, err := keytab.Load(ktp)
	if err != nil {
		fmt.Printf("keytab.Load err: %v\n", err)
	}
	cf, err := config.Load(cfp)
	if err != nil {
		fmt.Printf("config.Load err: %v\n", err)
	}

	options.KerberosServicePrincipleName = servicePrincipleName
	options.KerberosClient = client.NewWithKeytab(uname, realm, kt, cf)
	options.User = "zml"
	fmt.Printf("options: %#v\n", options)

	isconf, err := options.KerberosClient.IsConfigured()
	if err != nil {
		fmt.Printf("IsConfigured err: %v\n", err)
	}
	fmt.Printf("IsConfigured: %v\n", isconf)
	//*测试登录
	options.KerberosClient.Login()

	//*测试
	hdfsclient, err := hdfs.NewClient(options)

	if err != nil {
		fmt.Println(err)
	}
	return hdfsclient, nil
}

**Comment by fivvif** [comment]
Hello, how u solve this probem?@zmloong
