### ISSUE TITLE
When you use the go client to access the HDFS with kerberos and RBAC enabled, you cannot read and write properly. If RBAC is disabled, you can read and write properly

### ISSUE THREAD

**Issue by Tre2878** [colinmarc/hdfs#309]
Use go version: 1.19.4
Using the go library: github.com/colinmarc/hdfs
hdfs (version: 2.7.2, 3.3.4) : Enables kerberos and RBAC

Error message: no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED

kerberos authentication code snippet:
`func getKerberosClientWithKeytab(username, realm string, krb5ConfigPath, keytabPath string) *krb.Client {

    cfg, err := config.Load(krb5ConfigPath)
    if err != nil {
        log.Println("Couldn't load krb config:", err)
        return nil
    }
    kt, err := keytab.Load(keytabPath)
    if err != nil {
        log.Println("Couldn't load keytab:", err)
        return nil
    }

    client := krb.NewWithKeytab(username, realm, kt, cfg)
    err = client.Login()
    if err != nil {
        log.Println("Kerberos login failed: ", err)
        return nil
    } else {
        log.Println("Kerberos login success ")
    }
    return client
}`
Obtain the hdfs client code snippet after authentication:
`func NewHDFSClient(username, realm string, krb5ConfigPath, krb5CCName string, nodenames []string) *HDFSClient {

    conf, err := hadoopconf.LoadFromEnvironment()
    if err != nil {
        fmt.Println("Problem loading configuration: ", err)
    }
    options := hdfs.ClientOptionsFromConf(conf)

    options.Addresses = nodenames
    options.KerberosClient = getKerberosClientWithKeytab(username, realm, krb5ConfigPath, krb5CCName)
    options.KerberosServicePrincipleName = username
    options.User = "work"

    log.Println("options.Addresses:", options.Addresses)
    log.Println("options.KerberosClient:", options.KerberosClient)
    log.Println("options.KerberosServicePrincipleName:", options.KerberosServicePrincipleName)
    log.Println("options.User:", options.User)
    client, err := hdfs.NewClient(options)

    if err != nil {
        log.Panicln("client error:", err)
    }
    hdfsClient := &HDFSClient{
        Client: client,
    }
    return hdfsClient
}`

**Comment by fivvif** [comment]
Hello, how u solve this probem?@yuyanlei-8130
