### ISSUE TITLE
Libhdfs.so bindings for hdfs-go?

### ISSUE THREAD

**Issue by jimdowling** [colinmarc/hdfs#331]
Has anybody looked at integrating hdfs-go as a drop-in replacement for libhdfs.so ?

**Comment by colinmarc** [comment]
Hi @jimdowling,

I don’t know if anything like that. In general, calling go from C is extremely difficult because you need the go runtime.

Going to close this since it’s not really an issue with this library, but please don’t take that as me ending the discussion.
