### ISSUE TITLE
Sequence File

### ISSUE THREAD

**Issue by edwardsb** [colinmarc/hdfs#34]
It is possible to write to a sequence file using this lib? I looked through file_writer but it wasn't obvious where this might be taking place.

**Comment by colinmarc** [comment]
Hey! Totally, but you'll have to implement the sequencefile format. I've written a reader, here: https://github.com/stripe/sequins/tree/master/sequencefile

I've been meaning to implement a writer for a while, but haven't gotten around to it.

**Comment by edwardsb** [comment]
I am still in the early stages of learning golang. I have experience using the Java API, but I'll fork and give it a go (pun not intended).

**Comment by colinmarc** [comment]
@edwardsb there's a library up at https://github.com/colinmarc/sequencefile - write support should be coming in the next few days or so. Enjoy!
