### ISSUE TITLE
Auto discover client

### ISSUE THREAD

**Issue by crozzy** [colinmarc/hdfs#40]
@colinmarc I added this to my folk https://github.com/crozzy/hdfs/commit/ee32319d638c54fdb602ec170881837bc862bc63, would you be interested in a PR?

**Comment by crozzy** [comment]
https://github.com/crozzy/hdfs/blob/master/client_auto.go probably this is more descriptive :)

**Comment by colinmarc** [comment]
Hi! That seems useful, but I'd probably make a few changes to the interface. Please forgive my pickiness. It looks like the commits snuck into #38, so I'll leave comments there.

**Comment by colinmarc** [comment]
Fixed in #41 (thank you!)
