### ISSUE TITLE
a panic

### ISSUE THREAD

**Issue by gyustorm** [colinmarc/hdfs#42]
in order to upload a large file from my hdfs, i cut the file into multi blocks, but the file has only one shared blockreader, so when one block finished uploading it will close the blockreader, but others should use it, this make me very  confused.

**Comment by colinmarc** [comment]
Hi @gyustorm, sorry for the delay responding.

I'm not sure I completely understand your bug report - can you make a PR with a test case that panics?

**Comment by gyustorm** [comment]
Your hdfs.FileReader has only one blockReader, the FileReader implements os.File.ReadAt, so if i launch goroutines to read different ranges of the same file from hadoop for speeding up, then it will come to thread unsafe problem.

**Comment by colinmarc** [comment]
Ah, I understand. I don't make any guarantees about the thread safety of `FileReader`s, but maybe I should. Does it work if you try to have multiple `FileReader`s instead of just accessing the same one concurrently?

**Comment by gyustorm** [comment]
Hmm, maybe it works. Thanks for your reply.

**Comment by gyustorm** [comment]
Hmm, maybe it works. Thanks for your time.
