### ISSUE TITLE
Allow put from stdin

### ISSUE THREAD

**Issue by SuperQ** [colinmarc/hdfs#44]
It would be useful to be able to put from stdin.

For example:

```
tar -cz path/ | hdfs put - /path/tar.gz
```

The way `cmd/hdfs/put.go` is structured makes this a little tricky, but I think I can refactor this.

**Comment by colinmarc** [comment]
Ah, good idea!

**Comment by fdv** [comment]
👍 
I'd love to have it too, it's a killing feature for me.
