### ISSUE TITLE
fsck for hdfs

### ISSUE THREAD

**Issue by chaitanyalala** [colinmarc/hdfs#50]
Hi,

Are there any plans to add an fsck ? Similar functionality is provided by the hadoop client. Should be faster than using java client I feel.

**Comment by tyler-sommer** [comment]
Hi there,

I'm not the project maintainer but I had some free time to look into this. @colinmarc feel free to add your thoughts.

This project uses protocol buffers to communicate with HDFS NameNodes and DataNodes. As of Hadoop 2.7, fsck functionality is not exposed via these protocol buffers.

However, you can invoke fsck from the hadoop HTTP api[(ref)], but I'm not sure if @colinmarc wants to support the HTTP api in addition to protobuffer api.

It might be easier to just use the HTTP api yourself. For example, assuming default HDFS settings with a namenode running at 127.0.0.1, you can invoke fsck like:

```
curl http://127.0.0.1:50070/fsck
```


[(ref)]:https://github.com/apache/hadoop/blob/7d521a29eed62c4329b16034375bd5fb747a92a9/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DFSck.java#L262

**Comment by colinmarc** [comment]
If @tyler-sommer is right and there's no protobuf method (I don't see one either), that'd be add to include in this library.

I'm going to close this, but feel free to chime in with thoughts!
