### ISSUE TITLE
how map hadoop command line to api?

### ISSUE THREAD

**Issue by ljw7630** [colinmarc/hdfs#52]
I got a command like this:
hadoop fs -Dfs.default.name=hdfs://abc.com:8080 -Dhadoop.job.ugi=admin,supergroup -ls /foo/bar/

but I couldn't find any ugi setting in code. Any hint?

**Comment by colinmarc** [comment]
Hi! 

Try this: `HADOOP_USER_NAME="admin,supergroup" hdfs ls /foo/bar`

And let me know if it works.
