### ISSUE TITLE
append call failed with ERROR_APPLICATION (org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException)

### ISSUE THREAD

**Issue by 24** [colinmarc/hdfs#61]
hi colinmarc :

**Thank you for your   open source**

I have a problem  when  `for` append content to hdfs 
example:

```
writer, err := client.Create(fileName)	
writer.Close()

for i := 0; i < 10000; i++ {
		writer, err := client.Append(fileName)
                n, err := writer.Write([]byte("\nbar"))
		writer.Close()
}
```

then nameNode log error:

```
2016-12-01 01:42:20,828 INFO org.apache.hadoop.ipc.Server: IPC Server handler 7 on 9000,
 call org.apache.hadoop.hdfs.protocol.ClientProtocol.append from 192.168.10.209:60494
 Call#2 Retry#-1: org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException: 
Failed to APPEND_FILE /tmp/zhenglongqi/15.txt for go-hdfs-MHz41XTUfY3nheHd on 192.168.10.209 because this file lease is currently owned
 by go-hdfs-sm0fZSGAQA0uvyqR on 192.168.10.209
```
and golang error:

```
file_writer_test.go:323: err: append /tmp/ab/15.txt: append call failed with 
ERROR_APPLICATION (org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException)
```

`hadoop version : 2.7.3`
Single Node Cluster

hdfs-site.xml

```
<configuration> 
    <property>
      <name>dfs.replication</name>
      <value>1</value>
     </property>
  <property>
        <name>dfs.webhdfs.enabled</name>
        <value>true</value>
    </property>
  <property>
      <name>dfs.permissions.enabled</name>
      <value>false</value>
    </property>
 </configuration> 
```

when i use script 
```
#!/bin/bash
for i in {1..10000}
do
	hdfs="hdfs dfs -appendToFile ~/tmp/1 /data/2016-12-01/2016-12-01.tmp1"
	eval ${hdfs}
   echo "Welcome $i times"
done
```
this way ok . no error 

I don't know how to solve this  problem . 
do you have any idea ?
thanks

**Comment by colinmarc** [comment]
Huh - that certainly seems like a bug. Thanks for the report! If you have a chance to submit a test case for this behavior, that would be much appreciated.

**Comment by fnxnet** [comment]
Any news on this issue?

**Comment by zkchen310** [comment]
Any news on this issue?

**Comment by zkchen310** [comment]
I have fixed it:
block_write_stream.go, in method makePacket
```golang
func (s *blockWriteStream) makePacket() outboundPacket {
	packetLength := outboundPacketSize
	if s.buf.Len() < outboundPacketSize {
		packetLength = s.buf.Len()
	}
        // fill last chunk's margin with an individual packet
	marginSize := outboundChunkSize - (int(s.offset) % outboundChunkSize)
	if marginSize > 0 && packetLength > marginSize {
		packetLength = marginSize
	}
......
```

**Comment by colinmarc** [comment]
@zkchen310 - thanks very much for figuring that out! Sorry for any delinquency on my part. :)

**Comment by zhaijian** [comment]
hi,colinmarc:
- i check the newest code,the git version is d9614569203878ff04bb4420b929923949e855fc,
- but i encountered the same problem:
- when i first append,the err is "addBlock call failed with ERROR_APPLICATION (org.apache.hadoop.hdfs.server.namenode.NotReplicatedYetException)",and i append again, the err is "append call failed with ERROR_APPLICATION (org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException)"

code:
       
        nameServer := flag.String("nameserver", "", "The HDFS Name Node Address")
	user := flag.String("user", "", "The HDFS Visitor User")
	hdfsPath := flag.String("hdfsPath", "", "The HDFS  Which Will Write To HDFS")
	createFlag := flag.String("create", "", "create file flag")
	flag.Parse()
	mockStr := fmt.Sprintf(time.Now().String())
	client, err := hdfs.NewForUser(*nameServer, *user)
	utee.Chk(err)
	defer client.Close()
	if *createFlag != "" {
		w, err := client.Create(*hdfsPath)
		if err != nil {
			log.Println("CreateFile err", err)
		}
		_, err = w.Write([]byte(mockStr))
		log.Println("write err", err)
		w.Close()
		return
	}

	w, err := client.Append(*hdfsPath)
	//defer w.Close()
	if err != nil {
		log.Println("append err", err)
		return
	}
	_, err = w.Write([]byte(mockStr))
	log.Println("write err", err)
	w.Close()

 any advice? thank you!

**Comment by Revaapriyan** [comment]
I'm facing this issue now. Can anyone give me some solution ?

**Comment by mountainhua** [comment]
this issue is still exist in v2.3.0
