### ISSUE TITLE
allow to set rpc.NamenodeConnection for the hdfs client

### ISSUE THREAD

**Issue by advincze** [colinmarc/hdfs#62]
in my case I use a Socks proxy to access hdfs. I can already use the `rpc.WrapNamenodeConnection` to create an `*rpc.NamenodeConnection` but I cannot use it for the client.

This would work:
```
func NewForNamenode(namenode *rpc.NamenodeConnection) *Client {
	return &Client{namenode: namenode}
}
```

If if fits the project should I submit a PR ?

**Comment by colinmarc** [comment]
This is a good idea - I'd call it `NewForConnection` though.
