### ISSUE TITLE
Please generate a new release tag

### ISSUE THREAD

**Issue by gkalele** [colinmarc/hdfs#64]
Tools are picking up the latest release tag, which is Feb 2015.
Could you generate a new release tag ?

**Comment by colinmarc** [comment]
What tooling, out of curiosity? I'd be more inclined to just forgo releases altogether, although maybe it'd be nice to add binaries for the command-line tool.

**Comment by gkalele** [comment]
Glide.

It now supports semver versioning, and it is picking up v0.1.4 as the 'latest' release.

**Comment by colinmarc** [comment]
This is now done. Sorry about the delay 😓
