### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by TheCodeBuccaneer** [colinmarc/hdfs#66]
I am using the hdfs library in combination with windows and hadoop 2.7.3.

In Go I am using the below code:
`nodeaddress := "USERNAME:59351" //is Node address obtained from the Node of cluster overview of node manager, port changes on each new run of hadoop yarn`
`fmt.Println("Nodeaddress: ", nodeaddress)`
`client, err := hdfs.New(nodeaddress)`
`checkErr(err)`
`file, err := client.Open("/input/file1.txt")`
`fmt.Println("Open:", file)`
`checkErr(err)`

When I execute the script I get the below error:
>  Error: open /input/file1.txt: permission denied

I already tried to resolve it by adding:
`<property>
        <name>dfs.permissions</name>
        <value>false</value>
</property>`
to hdfs-site.xml, but this didn't resolve the issue.

Any ideas how to overcome the permissions error? Thanks

**Comment by colinmarc** [comment]
Hi there,

Unfortunately, I'm not really sure; you could try using [`NewForUser`](https://github.com/colinmarc/hdfs/blob/master/client.go#L67-L74), but it's been a while since I configured HDFS.

In any case, this looks like a configuration rather than a library issue, so I'm going to close it. Feel free to reopen if you figure out anything that points to a bug, though!

**Comment by TheCodeBuccaneer** [comment]
I got one step using the below code. 

`nodeaddress := "USERNAME:8042" 
`fmt.Println("Nodeaddress: ", nodeaddress)
`client, err := hdfs.New(nodeaddress)
`file, err := client.Open("/input/file1.txt")
`fmt.Println("Open:", file)
`checkErr(err)

But this time  I get the below error. Any ideas how to resolve this error or how to find further details on the cause of the error?

`unexpected` EOF

Once more thanks for your support!

**Comment by colinmarc** [comment]
`8042` might be the wrong port - I think that's the default webhdfs port, not the namenode port.
