### ISSUE TITLE
Test `df` in travis

### ISSUE THREAD

**Issue by junjieqian** [colinmarc/hdfs#68]
Hi, we need a function to report the HDFS usage, and it is in https://github.com/junjieqian/hdfs/commit/1d4700191d60ca86fec356add1fc6516609810fb (use `GetFsStatusRequestProto`). However, one problem I have is how to test this with travis? It seems impossible to do as the storage size changes in travis test from run to run.
Can you give me some hints or suggestions on this issue?

**Comment by colinmarc** [comment]
Hm, this should actually be possible if we make sure that the tests clean up after themselves completely. Fine to just test that the command works at all, though.
