### ISSUE TITLE
Truncate support questions on testing

### ISSUE THREAD

**Issue by junjieqian** [colinmarc/hdfs#72]
Hi, we would like to have random write feature with hdfs, and so `truncate` is needed. I implemented the `truncate` [feature](https://github.com/junjieqian/hdfs/commit/5983b69587ddc2f965a955886641b4bc4b53ceff), and tests pass on local machine. But it fails on Travis CI with error `truncate call failed with ERROR_NO_SUCH_METHOD (org.apache.hadoop.ipc.RpcNoSuchMethodException)`. Could anyone give me some hint on this?

**Comment by junjieqian** [comment]
It is caused by the tests on Travis uses Hadoop-2.6 which does not support `truncate` yet.

**Comment by colinmarc** [comment]
Yeah - there was some discussion in #31, but at the time there was no support in any of the tarballs we test with. I'm open to using a more recent tarball if that helps, though.

**Comment by junjieqian** [comment]
Hi @colinmarc , thanks for the reply! Cloudera's latest package is Hadoop-2.6, which does not support truncate. Hadoop-2.7.1 (Hortonworks' version) supports `truncate`, but the test does not return the correct truncated size, though my local tests work fine (hadoop-2.7.2).

I think `truncate` is good-to-have feature, but it is a little hassle to make Travis happy with its testing.
