### ISSUE TITLE
Not sure you intended to compare with 1 or 0

### ISSUE THREAD

**Issue by dlamblin** [colinmarc/hdfs#91]
https://github.com/colinmarc/hdfs/blob/1a4155475bdaa98f80f5e16c78a62f37de7c65f1/cmd/hdfs/complete.go#L32

```
$ hdfs 'complete'
ls rm mv mkdir touch chmod chown cat head tail du checksum get getmerge
$ hdfs 'complete' 'l'
ls rm mv mkdir touch chmod chown cat head tail du checksum get getmerge
$ hdfs 'complete' 'l l'
ls rm mv mkdir touch chmod chown cat head tail du checksum get getmerge
$ hdfs 'complete' 'l /v'
ls rm mv mkdir touch chmod chown cat head tail du checksum get getmerge
$ hdfs 'complete' 'l /v' /v
ls rm mv mkdir touch chmod chown cat head tail du checksum get getmerge
$ hdfs 'complete' 'l l /v'
 /var/

```

**Comment by colinmarc** [comment]
Somehow I never responded to this :)

The code is correct as written. `complete` either gets all separate words or one string with all the words squished together; that's what that branch is testing. So your example of

```
$ hdfs 'complete' 'l /v' /v
```

Shouldn't actually be possible. And changing the conditional to `if len(words) == 0` means we never complete the command at all.
