### ISSUE TITLE
bash completion only completes the last word.

### ISSUE THREAD

**Issue by dlamblin** [colinmarc/hdfs#92]
https://github.com/colinmarc/hdfs/blob/69e5098fa51e208a466aef9a5283b0101e6e4f54/cmd/hdfs/bash_completion#L9

As it currently stands, the completion of `hdfs l` is `hdfs ls`.  
The completion of `hdfs l /v` is `hdfs l /var/`.  
But moving the cursor back to `l` in `hdfs l /var/` does not complete `l` to `ls`.  

Also any directory that has 1000s of files (my case /var/) will hang in autocomplete.

**Comment by dlamblin** [comment]
#93 fixes completing the command when there are more arguments.

**Comment by colinmarc** [comment]
Hm, I wonder if there are performance problems in `Readdir`?
