### ISSUE TITLE
cp equivalent

### ISSUE THREAD

**Issue by rafaelkperes** [colinmarc/hdfs#94]
Is there anyway I can have a equivalent to ```hdfs dfs -cp <src-url> <dest-url>``` (as found [here](https://hortonworks.com/hadoop-tutorial/using-commandline-manage-files-hdfs/)) in the library?
As noted in the specified command:
> It is a tool used for large inter/intra-cluster copying

As of now, I did not find anyway to implement it using the library, without having to extract the data to my local environment.

**Comment by colinmarc** [comment]
Fun fact: I'm pretty sure that's actually what the command you mentioned does! There's no API for telling HDFS to copy to another HDFS cluster directly (that I know about; happy to be wrong).

I'd use `io.Copy` with `File` and a `FileWriter`.

Going to close this, but feel free to reopen if anything I said was incorrect.
